import type { PageId } from "./pages";

export const SECTIONS: Record<PageId, readonly string[]> = {
  intro: ["chat-tutorial", "session-info"],
  challenge: ["public-vs-enterprise", "data-feeding", "per-dept-problem"],
  vision: ["as-is", "to-be", "transition-benefit"],
  quantity: [
    "unstructured-importance",
    "update-sync",
    "lifecycle-issue",
    "quantity-breakdown",
    "key-question",
  ],
  security: [
    "access-need",
    "leak-scenario",
    "traditional-limit",
    "security-breakdown",
    "key-question",
  ],
  quality: [
    "hallucination-cause",
    "metadata-role",
    "filtering-need",
    "quality-breakdown",
    "key-question",
  ],
  requirements: ["three-pillars", "synthesis"],
  "existing-approaches": ["centralization", "data-lake", "gap-analysis"],
  wrapsody: [
    "overview",
    "tech-freshness",
    "tech-access",
    "tech-quality",
    "live-demo",
    "wrapsody-resources",
  ],
  agents: [
    "agents-overview",
    "k-assistant",
    "k-assistant-demo",
    "librarian",
    "librarian-demo",
    "domain-master",
    "domain-master-demo",
    "real-cases",
  ],
  fireside: [
    "concept",
    "integrated-hub",
    "mobile-extension",
    "open-api",
    "fireside-resources",
  ],
  conclusion: ["summary", "one-and-only", "cta"],
};

export const SECTION_DESCRIPTIONS: Record<string, string> = {
  "chat-tutorial": "챗봇 사용법 튜토리얼",
  "session-info": "발표자·세션 정보",
  "public-vs-enterprise": "퍼블릭 AI와 기업 AI의 차이",
  "data-feeding": "데이터 피딩이 결과 품질을 좌우함",
  "per-dept-problem": "부서별 개별 에이전트 구축의 문제",
  "as-is": "AS-IS: 부서별 에이전트 난립",
  "to-be": "TO-BE: 통합 AI 데이터 인프라",
  "transition-benefit": "통합 인프라 전환 시 이점",
  "unstructured-importance": "비정형 데이터",
  "update-sync": "데이터 지속 최신화 문제",
  "lifecycle-issue": "폐기 데이터 관리",
  "quantity-breakdown": "Quantity 요건 정리",
  "key-question": "핵심 질문 제시",
  "access-need": "권한 기반 접근 통제 필요성",
  "leak-scenario": "데이터 유출 시나리오",
  "traditional-limit": "기존 보안 방식의 한계",
  "security-breakdown": "Security 요건 정리",
  "hallucination-cause": "Garbage In Garbage Out",
  "metadata-role": "메타데이터의 역할",
  "filtering-need": "필터링 필요성",
  "quality-breakdown": "Quality 요건 정리",
  "three-pillars": "Quantity·Quality·Security 3대 기둥",
  synthesis: "세 요건의 종합",
  centralization: "문서 중앙화 방식",
  "data-lake": "데이터 레이크 방식",
  "gap-analysis": "두 방식이 남긴 공백",
  overview: "Wrapsody 개요",
  "tech-freshness": "자동 최신화 기술",
  "tech-access": "ACL 기반 접근 통제",
  "tech-quality": "메타데이터 품질 관리",
  "live-demo": "Wrapsody 실행 화면",
  "wrapsody-resources": "Wrapsody 브로슈어·공식 제품 페이지 링크",
  "agents-overview": "세 가지 에이전트 개요",
  "k-assistant": "K-Assistant 설명",
  "k-assistant-demo": "K-Assistant 실행 캡쳐",
  librarian: "Librarian 설명",
  "librarian-demo": "Librarian 실행 캡쳐",
  "domain-master": "Domain Knowledge Master 설명",
  "domain-master-demo": "Domain Master 실행 캡쳐",
  "real-cases": "파수 사내 운영 사례",
  concept: "Fireside 개념",
  "integrated-hub": "Wrapsody 3기능 + 메신저 통합 구조",
  "mobile-extension": "모바일 인터페이스 확장",
  "open-api": "개방형 API 연계",
  "fireside-resources": "Fireside 브로슈어·공식 제품 페이지 링크",
  summary: "결론 요약",
  "one-and-only": "One & Only 솔루션 메시지",
  cta: "Call to Action",
};
